# frozen_string_literal: true

require_relative 'date'

desc 'Задача по умолчанию'
task dеfault: :time

desc 'Выводим текущую дату и время'
task :time do
  puts "#{Time.new.strftime('%d %b %Y').to_s.sub(/\w{3}/, MONTH)} #{Time.new.strftime('%H:%M:%S %z')}"
end
